kind: pipeline
type: kubernetes
name: frontend

trigger:
  branch:
    - master

steps:
  # Build frontend
  - name: frontend_build
    image: node:lts-alpine
    commands:
      - cd client
      - npm install
      - npm run build

  # Build frontend docker image
  - name: frontend_build_docker
    image: plugins/docker
    settings:
      username:
        from_secret: registry_user
      password:
        from_secret: registry_pass
      repo: registry.local/car-admin-frontend
      tags: latest
      dockerfile: client/ci/Dockerfile
      context: client/
      insecure: true
      registry: registry.local
---
kind: pipeline
type: kubernetes
name: backend

trigger:
  branch:
    - master

steps:
  # Build backend
  - name: backend_build
    image: node:lts-alpine
    commands:
      - cd server
      - npm install
      - npm run build
      - npm install --production

  # Build backend docker image
  - name: frontend_build_docker
    image: plugins/docker
    settings:
      username:
        from_secret: registry_user
      password:
        from_secret: registry_pass
      repo: registry.local/car-admin-backend
      tags: latest
      dockerfile: server/ci/Dockerfile
      context: server/
      insecure: true
      registry: registry.local
