version: '3'

services:
  car-admin:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
        VARIANT: "14-buster"

    volumes:
      # Forwards the local Docker socket to the container.
      # - /var/run/docker.sock:/var/run/docker-host.sock 
      # Update this to wherever you want VS Code to mount the folder of your project
      - vsc-remote-containers:/workspace
      - car-database:/srv/data
      # - C:/Users/Kaloyan/work/personal/CarDB:/data

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: ["/bin/sh"]
    command: ["-c", "echo Container started ; trap \"exit 0\" 15; while sleep 1 & wait $$!; do :; done"]

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
volumes:
  vsc-remote-containers:
    external: true
  car-database:
    external: true